export interface Observation {
  id: number;
  birdid: number;
  userid: number;
  birdname: string | null;
  date: Date;
  time: string;
  note?: string;
  size: number;
  gender: string;
  imagepath: string;
  client_id?: string;
  latitude?: number;
  longitude?: number;
  created_at: Date;
  updated_at: Date;
}

// Représente le schéma réel Supabase + les colonnes ajoutées par la migration 001.
export const createObservationsTableSQL = `
CREATE TABLE IF NOT EXISTS public.observations (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  birdid    BIGINT NOT NULL REFERENCES public.birds(id),
  userid    BIGINT NOT NULL REFERENCES public.users(id),
  birdname  TEXT,
  date      DATE NOT NULL,
  time      TIME NOT NULL,
  note      TEXT,
  size      BIGINT NOT NULL,
  gender    CHARACTER VARYING NOT NULL,
  imagepath TEXT NOT NULL,
  client_id UUID,
  latitude  DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS observations_client_id_idx
  ON public.observations (client_id) WHERE client_id IS NOT NULL;
`;

const COLS = 'id, birdid, userid, birdname, date, time, note, size, gender, imagepath, client_id, latitude, longitude, created_at, updated_at';

export const insertObservationSQL = `
INSERT INTO observations (birdid, userid, birdname, date, time, note, size, gender, imagepath, client_id, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (client_id) WHERE client_id IS NOT NULL DO UPDATE SET updated_at = NOW()
RETURNING ${COLS};
`;

export const getObservationByIdSQL = `
SELECT ${COLS} FROM observations WHERE id = $1;
`;

export const getObservationsByUserIdSQL = `
SELECT o.id, o.birdid, o.userid, o.birdname, b.latinbirdname,
       o.date, o.time, o.note, o.size, o.gender, o.imagepath,
       o.client_id, o.latitude, o.longitude, o.created_at, o.updated_at
FROM observations o
LEFT JOIN birds b ON o.birdid = b.id
WHERE o.userid = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3;
`;

export const updateObservationSQL = `
UPDATE observations
SET birdid = $1, userid = $2, birdname = $3, date = $4, time = $5, note = $6,
    size = $7, gender = $8, imagepath = $9, latitude = $10, longitude = $11, updated_at = NOW()
WHERE id = $12
RETURNING ${COLS};
`;

export const deleteObservationSQL = `
DELETE FROM observations WHERE id = $1 RETURNING id;
`;

export const getAllObservationsSQL = `
SELECT ${COLS} FROM observations ORDER BY created_at DESC LIMIT $1 OFFSET $2;
`;
